### ISSUE TITLE
Add an assignment condition

### ISSUE THREAD

**Issue by jdesport** [cheminfo/polycalc#2]
##Define monomer ratio /monomer composition in chains
Addition of a function that describes the monomers contributions in each polymer ion (a range of composition allowed).

Analysis preference window, Molecular formula, List of monomers:
ex: DP(A)=DP(B)+1
OR: Monomer1 =(0.5 to 0.6)x monomer 2
A range of composition.

A and B were described as monomer 1 and 2 respectively with associated molecular formula.
DP stands for Degree of Polymerization = Nb of units

**Comment by lpatiny** [comment]
Implemented
