### ISSUE TITLE
REPORT Tab remove display options

### ISSUE THREAD

**Issue by jdesport** [cheminfo/polycalc#5]
Display chart quantity versus monomer
Display chart monomer vs mass
Display chart quantity versus mass

I suggest to erase the following options, which are found confusing.
Besides, quantity is a variable to be used with caution (dependent on Zone).
Monomer data will be processed in the new PLOT Tab.

**Comment by lpatiny** [comment]
Should we really remove those options or simple hide them by default ?

We should also probably in the report add more comments to explain to what correspond all the charts.
